### ISSUE TITLE
Change all `img` to `NuxtImg`

### ISSUE THREAD

**Issue by mickvandijke** [rcax-project/rcax-frontend-cross-platform#2]
https://image.nuxt.com/usage/nuxt-img?utm_source=lighthouse&utm_medium=lr#format

**Comment by HanBaichuan** [comment]
Hi there 🙂 can I push my branch and create a pr for this issue ? Big fan of RCA and wanna be helping RCA related projects!

**Comment by mickvandijke** [comment]
Hi @HanBaichuan ,

Sorry this issue is no longer relevant. However, PR's are always welcome!
